http:
  host: "localhost"
  port: "8080"

grpc:
  payment_client:
    host: "localhost"
    port: "50052"

  inventory_client:
    host: "localhost"
    port: "50051"

  iam_client:
    host: "localhost"
    port: "50053"

logger:
  level: "debug"

pg:
  host: "localhost"
  port: "5432"
  database: "order-service"
  user: "order-service-user"
  password: "order-service-password"
  sslmode: "disable"

kafka:
  brokers:
    - "localhost:9092"

ship_assembled_consumer:
  topic: "assembly.ship-assembled"
  group_id: "2"

order_paid_producer:
  topic: "order.paid"