grpc:
  host: "0.0.0.0"
  port: "50051"

pg:
  host: "localhost"
  port: "5433"
  database: "inventory-service"
  user: "inventory-service-user"
  password: "inventory-service-password"
  sslmode: "disable"

logger:
  level: "debug"