grpc:
  host: "0.0.0.0"
  port: "50051"

pg:
  host: "postgres-prod"
  port: "5433"
  database: "inventory_service"
  user: "MUST_BE_SET_VIA_ENV"
  password: "MUST_BE_SET_VIA_ENV"
  sslmode: "require"

logger:
  level: "error"