// Code generated for anemptyemptiness/Go-Rocket-App
// © Dmitry Nerusskov 2026.

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/anemptyemptiness/Go-Rocket-App/order/internal/model"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewOrderService creates a new instance of OrderService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOrderService(t interface {
	mock.TestingT
	Cleanup(func())
}) *OrderService {
	mock := &OrderService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// OrderService is an autogenerated mock type for the OrderService type
type OrderService struct {
	mock.Mock
}

type OrderService_Expecter struct {
	mock *mock.Mock
}

func (_m *OrderService) EXPECT() *OrderService_Expecter {
	return &OrderService_Expecter{mock: &_m.Mock}
}

// CancelOrder provides a mock function for the type OrderService
func (_mock *OrderService) CancelOrder(ctx context.Context, orderUUID uuid.UUID) error {
	ret := _mock.Called(ctx, orderUUID)

	if len(ret) == 0 {
		panic("no return value specified for Cancel")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, orderUUID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// OrderService_CancelOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Cancel'
type OrderService_CancelOrder_Call struct {
	*mock.Call
}

// CancelOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - orderUUID uuid.UUID
func (_e *OrderService_Expecter) CancelOrder(ctx interface{}, orderUUID interface{}) *OrderService_CancelOrder_Call {
	return &OrderService_CancelOrder_Call{Call: _e.mock.On("Cancel", ctx, orderUUID)}
}

func (_c *OrderService_CancelOrder_Call) Run(run func(ctx context.Context, orderUUID uuid.UUID)) *OrderService_CancelOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *OrderService_CancelOrder_Call) Return(err error) *OrderService_CancelOrder_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *OrderService_CancelOrder_Call) RunAndReturn(run func(ctx context.Context, orderUUID uuid.UUID) error) *OrderService_CancelOrder_Call {
	_c.Call.Return(run)
	return _c
}

// CreateOrder provides a mock function for the type OrderService
func (_mock *OrderService) CreateOrder(ctx context.Context, req model.CreateOrderRequest) (model.CreateOrderResponse, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 model.CreateOrderResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.CreateOrderRequest) (model.CreateOrderResponse, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.CreateOrderRequest) model.CreateOrderResponse); ok {
		r0 = returnFunc(ctx, req)
	} else {
		r0 = ret.Get(0).(model.CreateOrderResponse)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, model.CreateOrderRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// OrderService_CreateOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type OrderService_CreateOrder_Call struct {
	*mock.Call
}

// CreateOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - req model.CreateOrderRequest
func (_e *OrderService_Expecter) CreateOrder(ctx interface{}, req interface{}) *OrderService_CreateOrder_Call {
	return &OrderService_CreateOrder_Call{Call: _e.mock.On("Create", ctx, req)}
}

func (_c *OrderService_CreateOrder_Call) Run(run func(ctx context.Context, req model.CreateOrderRequest)) *OrderService_CreateOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model.CreateOrderRequest
		if args[1] != nil {
			arg1 = args[1].(model.CreateOrderRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *OrderService_CreateOrder_Call) Return(createOrderResponse model.CreateOrderResponse, err error) *OrderService_CreateOrder_Call {
	_c.Call.Return(createOrderResponse, err)
	return _c
}

func (_c *OrderService_CreateOrder_Call) RunAndReturn(run func(ctx context.Context, req model.CreateOrderRequest) (model.CreateOrderResponse, error)) *OrderService_CreateOrder_Call {
	_c.Call.Return(run)
	return _c
}

// GetOrder provides a mock function for the type OrderService
func (_mock *OrderService) GetOrder(ctx context.Context, orderUUID uuid.UUID) (model.Order, error) {
	ret := _mock.Called(ctx, orderUUID)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 model.Order
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (model.Order, error)); ok {
		return returnFunc(ctx, orderUUID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) model.Order); ok {
		r0 = returnFunc(ctx, orderUUID)
	} else {
		r0 = ret.Get(0).(model.Order)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, orderUUID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// OrderService_GetOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type OrderService_GetOrder_Call struct {
	*mock.Call
}

// GetOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - orderUUID uuid.UUID
func (_e *OrderService_Expecter) GetOrder(ctx interface{}, orderUUID interface{}) *OrderService_GetOrder_Call {
	return &OrderService_GetOrder_Call{Call: _e.mock.On("Get", ctx, orderUUID)}
}

func (_c *OrderService_GetOrder_Call) Run(run func(ctx context.Context, orderUUID uuid.UUID)) *OrderService_GetOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *OrderService_GetOrder_Call) Return(order model.Order, err error) *OrderService_GetOrder_Call {
	_c.Call.Return(order, err)
	return _c
}

func (_c *OrderService_GetOrder_Call) RunAndReturn(run func(ctx context.Context, orderUUID uuid.UUID) (model.Order, error)) *OrderService_GetOrder_Call {
	_c.Call.Return(run)
	return _c
}

// PayOrder provides a mock function for the type OrderService
func (_mock *OrderService) PayOrder(ctx context.Context, req model.PayOrderRequest, orderUUID uuid.UUID) (model.PayOrderResponse, error) {
	ret := _mock.Called(ctx, req, orderUUID)

	if len(ret) == 0 {
		panic("no return value specified for Pay")
	}

	var r0 model.PayOrderResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.PayOrderRequest, uuid.UUID) (model.PayOrderResponse, error)); ok {
		return returnFunc(ctx, req, orderUUID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.PayOrderRequest, uuid.UUID) model.PayOrderResponse); ok {
		r0 = returnFunc(ctx, req, orderUUID)
	} else {
		r0 = ret.Get(0).(model.PayOrderResponse)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, model.PayOrderRequest, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, req, orderUUID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// OrderService_PayOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Pay'
type OrderService_PayOrder_Call struct {
	*mock.Call
}

// PayOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - req model.PayOrderRequest
//   - orderUUID uuid.UUID
func (_e *OrderService_Expecter) PayOrder(ctx interface{}, req interface{}, orderUUID interface{}) *OrderService_PayOrder_Call {
	return &OrderService_PayOrder_Call{Call: _e.mock.On("Pay", ctx, req, orderUUID)}
}

func (_c *OrderService_PayOrder_Call) Run(run func(ctx context.Context, req model.PayOrderRequest, orderUUID uuid.UUID)) *OrderService_PayOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model.PayOrderRequest
		if args[1] != nil {
			arg1 = args[1].(model.PayOrderRequest)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *OrderService_PayOrder_Call) Return(payOrderResponse model.PayOrderResponse, err error) *OrderService_PayOrder_Call {
	_c.Call.Return(payOrderResponse, err)
	return _c
}

func (_c *OrderService_PayOrder_Call) RunAndReturn(run func(ctx context.Context, req model.PayOrderRequest, orderUUID uuid.UUID) (model.PayOrderResponse, error)) *OrderService_PayOrder_Call {
	_c.Call.Return(run)
	return _c
}
