// Code generated for anemptyemptiness/Go-Rocket-App
// © Dmitry Nerusskov 2026.

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/anemptyemptiness/Go-Rocket-App/platform/pkg/kafka"
	mock "github.com/stretchr/testify/mock"
)

// NewProducer creates a new instance of Producer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewProducer(t interface {
	mock.TestingT
	Cleanup(func())
}) *Producer {
	mock := &Producer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Producer is an autogenerated mock type for the Producer type
type Producer struct {
	mock.Mock
}

type Producer_Expecter struct {
	mock *mock.Mock
}

func (_m *Producer) EXPECT() *Producer_Expecter {
	return &Producer_Expecter{mock: &_m.Mock}
}

// Send provides a mock function for the type Producer
func (_mock *Producer) Send(ctx context.Context, msg *kafka.Message) error {
	ret := _mock.Called(ctx, msg)

	if len(ret) == 0 {
		panic("no return value specified for Send")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *kafka.Message) error); ok {
		r0 = returnFunc(ctx, msg)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Producer_Send_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Send'
type Producer_Send_Call struct {
	*mock.Call
}

// Send is a helper method to define mock.On call
//   - ctx context.Context
//   - msg *kafka.Message
func (_e *Producer_Expecter) Send(ctx interface{}, msg interface{}) *Producer_Send_Call {
	return &Producer_Send_Call{Call: _e.mock.On("Send", ctx, msg)}
}

func (_c *Producer_Send_Call) Run(run func(ctx context.Context, msg *kafka.Message)) *Producer_Send_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *kafka.Message
		if args[1] != nil {
			arg1 = args[1].(*kafka.Message)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Producer_Send_Call) Return(err error) *Producer_Send_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Producer_Send_Call) RunAndReturn(run func(ctx context.Context, msg *kafka.Message) error) *Producer_Send_Call {
	_c.Call.Return(run)
	return _c
}
