// Code generated for anemptyemptiness/Go-Rocket-App
// © Dmitry Nerusskov 2026.

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/anemptyemptiness/Go-Rocket-App/assembly/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// NewShipAssembledProducerService creates a new instance of ShipAssembledProducerService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewShipAssembledProducerService(t interface {
	mock.TestingT
	Cleanup(func())
}) *ShipAssembledProducerService {
	mock := &ShipAssembledProducerService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ShipAssembledProducerService is an autogenerated mock type for the ShipAssembledProducerService type
type ShipAssembledProducerService struct {
	mock.Mock
}

type ShipAssembledProducerService_Expecter struct {
	mock *mock.Mock
}

func (_m *ShipAssembledProducerService) EXPECT() *ShipAssembledProducerService_Expecter {
	return &ShipAssembledProducerService_Expecter{mock: &_m.Mock}
}

// Produce provides a mock function for the type ShipAssembledProducerService
func (_mock *ShipAssembledProducerService) Produce(ctx context.Context, event model.ShipAssembledEvent) error {
	ret := _mock.Called(ctx, event)

	if len(ret) == 0 {
		panic("no return value specified for Produce")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.ShipAssembledEvent) error); ok {
		r0 = returnFunc(ctx, event)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ShipAssembledProducerService_Produce_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Produce'
type ShipAssembledProducerService_Produce_Call struct {
	*mock.Call
}

// Produce is a helper method to define mock.On call
//   - ctx context.Context
//   - event model.ShipAssembledEvent
func (_e *ShipAssembledProducerService_Expecter) Produce(ctx interface{}, event interface{}) *ShipAssembledProducerService_Produce_Call {
	return &ShipAssembledProducerService_Produce_Call{Call: _e.mock.On("Produce", ctx, event)}
}

func (_c *ShipAssembledProducerService_Produce_Call) Run(run func(ctx context.Context, event model.ShipAssembledEvent)) *ShipAssembledProducerService_Produce_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model.ShipAssembledEvent
		if args[1] != nil {
			arg1 = args[1].(model.ShipAssembledEvent)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ShipAssembledProducerService_Produce_Call) Return(err error) *ShipAssembledProducerService_Produce_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ShipAssembledProducerService_Produce_Call) RunAndReturn(run func(ctx context.Context, event model.ShipAssembledEvent) error) *ShipAssembledProducerService_Produce_Call {
	_c.Call.Return(run)
	return _c
}
