// Code generated for anemptyemptiness/Go-Rocket-App
// © Dmitry Nerusskov 2026.

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewSleeper creates a new instance of Sleeper. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSleeper(t interface {
	mock.TestingT
	Cleanup(func())
}) *Sleeper {
	mock := &Sleeper{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Sleeper is an autogenerated mock type for the Sleeper type
type Sleeper struct {
	mock.Mock
}

type Sleeper_Expecter struct {
	mock *mock.Mock
}

func (_m *Sleeper) EXPECT() *Sleeper_Expecter {
	return &Sleeper_Expecter{mock: &_m.Mock}
}

// Sleep provides a mock function for the type Sleeper
func (_mock *Sleeper) Sleep() int64 {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Sleep")
	}

	var r0 int64
	if returnFunc, ok := ret.Get(0).(func() int64); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(int64)
	}
	return r0
}

// Sleeper_Sleep_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Sleep'
type Sleeper_Sleep_Call struct {
	*mock.Call
}

// Sleep is a helper method to define mock.On call
func (_e *Sleeper_Expecter) Sleep() *Sleeper_Sleep_Call {
	return &Sleeper_Sleep_Call{Call: _e.mock.On("Sleep")}
}

func (_c *Sleeper_Sleep_Call) Run(run func()) *Sleeper_Sleep_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Sleeper_Sleep_Call) Return(n int64) *Sleeper_Sleep_Call {
	_c.Call.Return(n)
	return _c
}

func (_c *Sleeper_Sleep_Call) RunAndReturn(run func() int64) *Sleeper_Sleep_Call {
	_c.Call.Return(run)
	return _c
}
