// Code generated for anemptyemptiness/Go-Rocket-App
// © Dmitry Nerusskov 2026.

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/anemptyemptiness/Go-Rocket-App/iam/internal/model"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewSessionRepository creates a new instance of SessionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSessionRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *SessionRepository {
	mock := &SessionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// SessionRepository is an autogenerated mock type for the SessionRepository type
type SessionRepository struct {
	mock.Mock
}

type SessionRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *SessionRepository) EXPECT() *SessionRepository_Expecter {
	return &SessionRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type SessionRepository
func (_mock *SessionRepository) Create(ctx context.Context, user model.User) (uuid.UUID, error) {
	ret := _mock.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 uuid.UUID
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.User) (uuid.UUID, error)); ok {
		return returnFunc(ctx, user)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.User) uuid.UUID); ok {
		r0 = returnFunc(ctx, user)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, model.User) error); ok {
		r1 = returnFunc(ctx, user)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// SessionRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type SessionRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - user model.User
func (_e *SessionRepository_Expecter) Create(ctx interface{}, user interface{}) *SessionRepository_Create_Call {
	return &SessionRepository_Create_Call{Call: _e.mock.On("Create", ctx, user)}
}

func (_c *SessionRepository_Create_Call) Run(run func(ctx context.Context, user model.User)) *SessionRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model.User
		if args[1] != nil {
			arg1 = args[1].(model.User)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *SessionRepository_Create_Call) Return(uUID uuid.UUID, err error) *SessionRepository_Create_Call {
	_c.Call.Return(uUID, err)
	return _c
}

func (_c *SessionRepository_Create_Call) RunAndReturn(run func(ctx context.Context, user model.User) (uuid.UUID, error)) *SessionRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type SessionRepository
func (_mock *SessionRepository) Delete(ctx context.Context, sessionUUID uuid.UUID) error {
	ret := _mock.Called(ctx, sessionUUID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, sessionUUID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// SessionRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type SessionRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionUUID uuid.UUID
func (_e *SessionRepository_Expecter) Delete(ctx interface{}, sessionUUID interface{}) *SessionRepository_Delete_Call {
	return &SessionRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, sessionUUID)}
}

func (_c *SessionRepository_Delete_Call) Run(run func(ctx context.Context, sessionUUID uuid.UUID)) *SessionRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *SessionRepository_Delete_Call) Return(err error) *SessionRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *SessionRepository_Delete_Call) RunAndReturn(run func(ctx context.Context, sessionUUID uuid.UUID) error) *SessionRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByUUID provides a mock function for the type SessionRepository
func (_mock *SessionRepository) GetByUUID(ctx context.Context, sessionUUID uuid.UUID) (model.Session, error) {
	ret := _mock.Called(ctx, sessionUUID)

	if len(ret) == 0 {
		panic("no return value specified for GetByUUID")
	}

	var r0 model.Session
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (model.Session, error)); ok {
		return returnFunc(ctx, sessionUUID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) model.Session); ok {
		r0 = returnFunc(ctx, sessionUUID)
	} else {
		r0 = ret.Get(0).(model.Session)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, sessionUUID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// SessionRepository_GetByUUID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByUUID'
type SessionRepository_GetByUUID_Call struct {
	*mock.Call
}

// GetByUUID is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionUUID uuid.UUID
func (_e *SessionRepository_Expecter) GetByUUID(ctx interface{}, sessionUUID interface{}) *SessionRepository_GetByUUID_Call {
	return &SessionRepository_GetByUUID_Call{Call: _e.mock.On("GetByUUID", ctx, sessionUUID)}
}

func (_c *SessionRepository_GetByUUID_Call) Run(run func(ctx context.Context, sessionUUID uuid.UUID)) *SessionRepository_GetByUUID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *SessionRepository_GetByUUID_Call) Return(session model.Session, err error) *SessionRepository_GetByUUID_Call {
	_c.Call.Return(session, err)
	return _c
}

func (_c *SessionRepository_GetByUUID_Call) RunAndReturn(run func(ctx context.Context, sessionUUID uuid.UUID) (model.Session, error)) *SessionRepository_GetByUUID_Call {
	_c.Call.Return(run)
	return _c
}
