// Code generated for anemptyemptiness/Go-Rocket-App
// © Dmitry Nerusskov 2026.

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/anemptyemptiness/Go-Rocket-App/inventory/internal/model/entity"
	"github.com/anemptyemptiness/Go-Rocket-App/inventory/internal/service/input"
	mock "github.com/stretchr/testify/mock"
)

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

type Repository_Expecter struct {
	mock *mock.Mock
}

func (_m *Repository) EXPECT() *Repository_Expecter {
	return &Repository_Expecter{mock: &_m.Mock}
}

// GetPart provides a mock function for the type Repository
func (_mock *Repository) GetPart(ctx context.Context, uuid string) (entity.Part, error) {
	ret := _mock.Called(ctx, uuid)

	if len(ret) == 0 {
		panic("no return value specified for GetPart")
	}

	var r0 entity.Part
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (entity.Part, error)); ok {
		return returnFunc(ctx, uuid)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) entity.Part); ok {
		r0 = returnFunc(ctx, uuid)
	} else {
		r0 = ret.Get(0).(entity.Part)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, uuid)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Repository_GetPart_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPart'
type Repository_GetPart_Call struct {
	*mock.Call
}

// GetPart is a helper method to define mock.On call
//   - ctx context.Context
//   - uuid string
func (_e *Repository_Expecter) GetPart(ctx interface{}, uuid interface{}) *Repository_GetPart_Call {
	return &Repository_GetPart_Call{Call: _e.mock.On("GetPart", ctx, uuid)}
}

func (_c *Repository_GetPart_Call) Run(run func(ctx context.Context, uuid string)) *Repository_GetPart_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Repository_GetPart_Call) Return(part entity.Part, err error) *Repository_GetPart_Call {
	_c.Call.Return(part, err)
	return _c
}

func (_c *Repository_GetPart_Call) RunAndReturn(run func(ctx context.Context, uuid string) (entity.Part, error)) *Repository_GetPart_Call {
	_c.Call.Return(run)
	return _c
}

// ListParts provides a mock function for the type Repository
func (_mock *Repository) ListParts(ctx context.Context, filter input.PartFilter) ([]entity.Part, error) {
	ret := _mock.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for ListParts")
	}

	var r0 []entity.Part
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, input.PartFilter) ([]entity.Part, error)); ok {
		return returnFunc(ctx, filter)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, input.PartFilter) []entity.Part); ok {
		r0 = returnFunc(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Part)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, input.PartFilter) error); ok {
		r1 = returnFunc(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Repository_ListParts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListParts'
type Repository_ListParts_Call struct {
	*mock.Call
}

// ListParts is a helper method to define mock.On call
//   - ctx context.Context
//   - filter input.PartFilter
func (_e *Repository_Expecter) ListParts(ctx interface{}, filter interface{}) *Repository_ListParts_Call {
	return &Repository_ListParts_Call{Call: _e.mock.On("ListParts", ctx, filter)}
}

func (_c *Repository_ListParts_Call) Run(run func(ctx context.Context, filter input.PartFilter)) *Repository_ListParts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 input.PartFilter
		if args[1] != nil {
			arg1 = args[1].(input.PartFilter)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Repository_ListParts_Call) Return(parts []entity.Part, err error) *Repository_ListParts_Call {
	_c.Call.Return(parts, err)
	return _c
}

func (_c *Repository_ListParts_Call) RunAndReturn(run func(ctx context.Context, filter input.PartFilter) ([]entity.Part, error)) *Repository_ListParts_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateReservedBatch provides a mock function for the type Repository
func (_mock *Repository) UpdateReservedBatch(ctx context.Context, parts []entity.Part) error {
	ret := _mock.Called(ctx, parts)

	if len(ret) == 0 {
		panic("no return value specified for UpdateReservedBatch")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []entity.Part) error); ok {
		r0 = returnFunc(ctx, parts)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Repository_UpdateReservedBatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateReservedBatch'
type Repository_UpdateReservedBatch_Call struct {
	*mock.Call
}

// UpdateReservedBatch is a helper method to define mock.On call
//   - ctx context.Context
//   - parts []entity.Part
func (_e *Repository_Expecter) UpdateReservedBatch(ctx interface{}, parts interface{}) *Repository_UpdateReservedBatch_Call {
	return &Repository_UpdateReservedBatch_Call{Call: _e.mock.On("UpdateReservedBatch", ctx, parts)}
}

func (_c *Repository_UpdateReservedBatch_Call) Run(run func(ctx context.Context, parts []entity.Part)) *Repository_UpdateReservedBatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []entity.Part
		if args[1] != nil {
			arg1 = args[1].([]entity.Part)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Repository_UpdateReservedBatch_Call) Return(err error) *Repository_UpdateReservedBatch_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Repository_UpdateReservedBatch_Call) RunAndReturn(run func(ctx context.Context, parts []entity.Part) error) *Repository_UpdateReservedBatch_Call {
	_c.Call.Return(run)
	return _c
}
