// Code generated for anemptyemptiness/Go-Rocket-App
// © Dmitry Nerusskov 2026.

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/anemptyemptiness/Go-Rocket-App/assembly/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// NewAssembleService creates a new instance of AssembleService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAssembleService(t interface {
	mock.TestingT
	Cleanup(func())
}) *AssembleService {
	mock := &AssembleService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// AssembleService is an autogenerated mock type for the AssembleService type
type AssembleService struct {
	mock.Mock
}

type AssembleService_Expecter struct {
	mock *mock.Mock
}

func (_m *AssembleService) EXPECT() *AssembleService_Expecter {
	return &AssembleService_Expecter{mock: &_m.Mock}
}

// ShipAssemble provides a mock function for the type AssembleService
func (_mock *AssembleService) ShipAssemble(ctx context.Context, event model.ShipAssembledEvent) error {
	ret := _mock.Called(ctx, event)

	if len(ret) == 0 {
		panic("no return value specified for ShipAssemble")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.ShipAssembledEvent) error); ok {
		r0 = returnFunc(ctx, event)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// AssembleService_ShipAssemble_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ShipAssemble'
type AssembleService_ShipAssemble_Call struct {
	*mock.Call
}

// ShipAssemble is a helper method to define mock.On call
//   - ctx context.Context
//   - event model.ShipAssembledEvent
func (_e *AssembleService_Expecter) ShipAssemble(ctx interface{}, event interface{}) *AssembleService_ShipAssemble_Call {
	return &AssembleService_ShipAssemble_Call{Call: _e.mock.On("ShipAssemble", ctx, event)}
}

func (_c *AssembleService_ShipAssemble_Call) Run(run func(ctx context.Context, event model.ShipAssembledEvent)) *AssembleService_ShipAssemble_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model.ShipAssembledEvent
		if args[1] != nil {
			arg1 = args[1].(model.ShipAssembledEvent)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *AssembleService_ShipAssemble_Call) Return(err error) *AssembleService_ShipAssemble_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *AssembleService_ShipAssemble_Call) RunAndReturn(run func(ctx context.Context, event model.ShipAssembledEvent) error) *AssembleService_ShipAssemble_Call {
	_c.Call.Return(run)
	return _c
}
