// Code generated for anemptyemptiness/Go-Rocket-App
// © Dmitry Nerusskov 2026.

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/anemptyemptiness/Go-Rocket-App/order/internal/model"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

type Repository_Expecter struct {
	mock *mock.Mock
}

func (_m *Repository) EXPECT() *Repository_Expecter {
	return &Repository_Expecter{mock: &_m.Mock}
}

// CreateOrder provides a mock function for the type Repository
func (_mock *Repository) CreateOrder(ctx context.Context, order model.Order) error {
	ret := _mock.Called(ctx, order)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.Order) error); ok {
		r0 = returnFunc(ctx, order)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Repository_CreateOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type Repository_CreateOrder_Call struct {
	*mock.Call
}

// CreateOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - order model.Order
func (_e *Repository_Expecter) CreateOrder(ctx interface{}, order interface{}) *Repository_CreateOrder_Call {
	return &Repository_CreateOrder_Call{Call: _e.mock.On("Create", ctx, order)}
}

func (_c *Repository_CreateOrder_Call) Run(run func(ctx context.Context, order model.Order)) *Repository_CreateOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model.Order
		if args[1] != nil {
			arg1 = args[1].(model.Order)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Repository_CreateOrder_Call) Return(err error) *Repository_CreateOrder_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Repository_CreateOrder_Call) RunAndReturn(run func(ctx context.Context, order model.Order) error) *Repository_CreateOrder_Call {
	_c.Call.Return(run)
	return _c
}

// GetOrder provides a mock function for the type Repository
func (_mock *Repository) GetOrder(ctx context.Context, orderUUID uuid.UUID) (model.Order, error) {
	ret := _mock.Called(ctx, orderUUID)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 model.Order
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (model.Order, error)); ok {
		return returnFunc(ctx, orderUUID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) model.Order); ok {
		r0 = returnFunc(ctx, orderUUID)
	} else {
		r0 = ret.Get(0).(model.Order)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, orderUUID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Repository_GetOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type Repository_GetOrder_Call struct {
	*mock.Call
}

// GetOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - orderUUID uuid.UUID
func (_e *Repository_Expecter) GetOrder(ctx interface{}, orderUUID interface{}) *Repository_GetOrder_Call {
	return &Repository_GetOrder_Call{Call: _e.mock.On("Get", ctx, orderUUID)}
}

func (_c *Repository_GetOrder_Call) Run(run func(ctx context.Context, orderUUID uuid.UUID)) *Repository_GetOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Repository_GetOrder_Call) Return(order model.Order, err error) *Repository_GetOrder_Call {
	_c.Call.Return(order, err)
	return _c
}

func (_c *Repository_GetOrder_Call) RunAndReturn(run func(ctx context.Context, orderUUID uuid.UUID) (model.Order, error)) *Repository_GetOrder_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateOrder provides a mock function for the type Repository
func (_mock *Repository) UpdateOrder(ctx context.Context, order model.Order) error {
	ret := _mock.Called(ctx, order)

	if len(ret) == 0 {
		panic("no return value specified for UpdateOrder")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.Order) error); ok {
		r0 = returnFunc(ctx, order)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Repository_UpdateOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateOrder'
type Repository_UpdateOrder_Call struct {
	*mock.Call
}

// UpdateOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - order model.Order
func (_e *Repository_Expecter) UpdateOrder(ctx interface{}, order interface{}) *Repository_UpdateOrder_Call {
	return &Repository_UpdateOrder_Call{Call: _e.mock.On("UpdateOrder", ctx, order)}
}

func (_c *Repository_UpdateOrder_Call) Run(run func(ctx context.Context, order model.Order)) *Repository_UpdateOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model.Order
		if args[1] != nil {
			arg1 = args[1].(model.Order)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Repository_UpdateOrder_Call) Return(err error) *Repository_UpdateOrder_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Repository_UpdateOrder_Call) RunAndReturn(run func(ctx context.Context, order model.Order) error) *Repository_UpdateOrder_Call {
	_c.Call.Return(run)
	return _c
}
