// Code generated for anemptyemptiness/Go-Rocket-App
// © Dmitry Nerusskov 2026.

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/anemptyemptiness/Go-Rocket-App/order/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// NewInventoryClient creates a new instance of InventoryClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewInventoryClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *InventoryClient {
	mock := &InventoryClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// InventoryClient is an autogenerated mock type for the InventoryClient type
type InventoryClient struct {
	mock.Mock
}

type InventoryClient_Expecter struct {
	mock *mock.Mock
}

func (_m *InventoryClient) EXPECT() *InventoryClient_Expecter {
	return &InventoryClient_Expecter{mock: &_m.Mock}
}

// ListParts provides a mock function for the type InventoryClient
func (_mock *InventoryClient) ListParts(ctx context.Context, req model.ListPartsClientRequest) (model.ListPartsClientResponse, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for ListParts")
	}

	var r0 model.ListPartsClientResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.ListPartsClientRequest) (model.ListPartsClientResponse, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.ListPartsClientRequest) model.ListPartsClientResponse); ok {
		r0 = returnFunc(ctx, req)
	} else {
		r0 = ret.Get(0).(model.ListPartsClientResponse)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, model.ListPartsClientRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// InventoryClient_ListParts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListParts'
type InventoryClient_ListParts_Call struct {
	*mock.Call
}

// ListParts is a helper method to define mock.On call
//   - ctx context.Context
//   - req model.ListPartsClientRequest
func (_e *InventoryClient_Expecter) ListParts(ctx interface{}, req interface{}) *InventoryClient_ListParts_Call {
	return &InventoryClient_ListParts_Call{Call: _e.mock.On("ListParts", ctx, req)}
}

func (_c *InventoryClient_ListParts_Call) Run(run func(ctx context.Context, req model.ListPartsClientRequest)) *InventoryClient_ListParts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model.ListPartsClientRequest
		if args[1] != nil {
			arg1 = args[1].(model.ListPartsClientRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *InventoryClient_ListParts_Call) Return(listPartsClientResponse model.ListPartsClientResponse, err error) *InventoryClient_ListParts_Call {
	_c.Call.Return(listPartsClientResponse, err)
	return _c
}

func (_c *InventoryClient_ListParts_Call) RunAndReturn(run func(ctx context.Context, req model.ListPartsClientRequest) (model.ListPartsClientResponse, error)) *InventoryClient_ListParts_Call {
	_c.Call.Return(run)
	return _c
}
