// Code generated for anemptyemptiness/Go-Rocket-App
// © Dmitry Nerusskov 2026.

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/anemptyemptiness/Go-Rocket-App/order/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// NewOrderPaidProducerService creates a new instance of OrderPaidProducerService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOrderPaidProducerService(t interface {
	mock.TestingT
	Cleanup(func())
}) *OrderPaidProducerService {
	mock := &OrderPaidProducerService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// OrderPaidProducerService is an autogenerated mock type for the OrderPaidProducerService type
type OrderPaidProducerService struct {
	mock.Mock
}

type OrderPaidProducerService_Expecter struct {
	mock *mock.Mock
}

func (_m *OrderPaidProducerService) EXPECT() *OrderPaidProducerService_Expecter {
	return &OrderPaidProducerService_Expecter{mock: &_m.Mock}
}

// Produce provides a mock function for the type OrderPaidProducerService
func (_mock *OrderPaidProducerService) Produce(ctx context.Context, event model.OrderPaidEvent) error {
	ret := _mock.Called(ctx, event)

	if len(ret) == 0 {
		panic("no return value specified for Produce")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.OrderPaidEvent) error); ok {
		r0 = returnFunc(ctx, event)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// OrderPaidProducerService_Produce_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Produce'
type OrderPaidProducerService_Produce_Call struct {
	*mock.Call
}

// Produce is a helper method to define mock.On call
//   - ctx context.Context
//   - event model.OrderPaidEvent
func (_e *OrderPaidProducerService_Expecter) Produce(ctx interface{}, event interface{}) *OrderPaidProducerService_Produce_Call {
	return &OrderPaidProducerService_Produce_Call{Call: _e.mock.On("Produce", ctx, event)}
}

func (_c *OrderPaidProducerService_Produce_Call) Run(run func(ctx context.Context, event model.OrderPaidEvent)) *OrderPaidProducerService_Produce_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model.OrderPaidEvent
		if args[1] != nil {
			arg1 = args[1].(model.OrderPaidEvent)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *OrderPaidProducerService_Produce_Call) Return(err error) *OrderPaidProducerService_Produce_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *OrderPaidProducerService_Produce_Call) RunAndReturn(run func(ctx context.Context, event model.OrderPaidEvent) error) *OrderPaidProducerService_Produce_Call {
	_c.Call.Return(run)
	return _c
}
